### ISSUE TITLE
v0.2.17 fails to build on Intel MacOS 15.5 (24F74) x86_64-apple-darwin

### ISSUE THREAD

**Issue by tschundler** [RustAudio/coreaudio-sys#116]
```
$ cargo build
   Compiling glob v0.3.2
   Compiling proc-macro2 v1.0.95
   Compiling libc v0.2.174
   Compiling unicode-ident v1.0.18
   Compiling memchr v2.7.5
   Compiling cfg-if v1.0.1
   Compiling minimal-lexical v0.2.1
   Compiling regex-syntax v0.8.5
   Compiling bindgen v0.72.0
   Compiling either v1.15.0
   Compiling shlex v1.3.0
   Compiling bitflags v2.9.1
   Compiling libloading v0.8.8
   Compiling rustc-hash v2.1.1
   Compiling itertools v0.13.0
   Compiling nom v7.1.3
   Compiling clang-sys v1.8.1
   Compiling quote v1.0.40
   Compiling syn v2.0.104
   Compiling regex-automata v0.4.9
   Compiling cexpr v0.6.0
   Compiling regex v1.11.1
   Compiling coreaudio-sys v0.2.17 (/Users/ted/rust/coreaudio-sys)
error: failed to run custom build command for `coreaudio-sys v0.2.17 (/Users/ted/rust/coreaudio-sys)`

Caused by:
  process didn't exit successfully: `/Users/ted/rust/coreaudio-sys/target/debug/build/coreaudio-sys-05ad3f4cfb6f2ad7/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH
  cargo:rustc-link-lib=framework=AudioUnit
  cargo:rustc-link-lib=framework=AudioToolbox
  cargo:rustc-link-lib=framework=CoreAudio
  cargo:rustc-link-lib=framework=OpenAL
  cargo:rustc-link-lib=framework=CoreMIDI
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  /Users/ted/rust/coreaudio-sys/coreaudio.h:1:10: fatal error: 'AudioUnit/AudioUnit.h' file not found

  thread 'main' panicked at /Users/ted/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bindgen-0.72.0/lib.rs:917:13:
  assertion `left == right` failed: "x86_64-apple-darwin" "x86_64-apple-darwin"
    left: 4
   right: 8
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Forcing previous 0.2.16 builds OK.

```
$ xcrun --sdk macosx --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk
$ find $(xcrun --sdk macosx --show-sdk-path) -name "AudioUnit.h"
/Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/AudioUnit.framework/Versions/A/Headers/AudioUnit.h
/Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/AudioToolbox.framework/Versions/A/Headers/AudioUnit.h
```

I also tried `export COREAUDIO_SDK_PATH=$(xcrun --sdk macosx --show-sdk-path)` which didn't help.

I did try in an ARM macbook had a different build error.

I suspect this is either an issue with `bindgen` itself or the use of it here since that's all that changed.

**Comment by tschundler** [comment]
...trying to bisect to find the version of `bindgen` where it breaks, updating `Cargo.toml` and running `cargo clean && rm Cargo.lock && cargo build`

and now it always works...

unsetting `COREAUDIO_SDK_PATH` and it breaks

I guess I missed a `cargo clean` or `rm Cargo.lock` or something after that change?


no... I can't get it to fail again.

fwiw, I also added this to try to understand the path issue:

```
index f3373cd8d0..a89afc1937 100644
--- a/build.rs
+++ b/build.rs
@@ -4,6 +4,7 @@
     // Use environment variable if set
     println!("cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH");
     if let Ok(path) = std::env::var("COREAUDIO_SDK_PATH") {
+        println!("cargo:warning=Using SDK path from env: {}", path);
         return Ok(path);
     }
 
@@ -29,6 +30,7 @@
         .output()?
         .stdout;
     let prefix_str = std::str::from_utf8(&output).expect("invalid output from `xcrun`");
+    println!("cargo:warning=Using SDK path: {}", prefix_str.trim_end());
     Ok(prefix_str.trim_end().to_string())
 }
```

and it is working even automatically setting the path.

**Comment by tschundler** [comment]
... but it is still not working when used from bevy... (which is what lead me to testing with it separately). With the patch to `build.rs`, it looks like `xcrun` worked out ok:

```
warning: coreaudio-sys@0.2.17: Using SDK path from env: /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk
error: failed to run custom build command for `coreaudio-sys v0.2.17`

Caused by:
  process didn't exit successfully: `/Users/ted/rust/led-graph/target/debug/build/coreaudio-sys-56bd2bf5c20f1b9e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH
  cargo:warning=Using SDK path from env: /Library/Developer/CommandLineTools/SDKs/MacOSX15.5.sdk
  cargo:rustc-link-lib=framework=AudioUnit
  cargo:rustc-link-lib=framework=CoreAudio
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  /Users/ted/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/coreaudio-sys-0.2.17/coreaudio.h:1:10: fatal error: 'AudioUnit/AudioUnit.h' file not found

  thread 'main' panicked at /Users/ted/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bindgen-0.72.0/lib.rs:917:13:
  assertion `left == right` failed: "x86_64-apple-darwin" "x86_64-apple-darwin"
    left: 4
   right: 8
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by tschundler** [comment]
this `assertion `left == right` failed: "x86_64-apple-darwin" "x86_64-apple-darwin"` is particularly mysterious... "x86_64-apple-darwin" == "x86_64-apple-darwin" so how is that failing?

...and the fix building bevy is
```
$ export BINDGEN_EXTRA_CLANG_ARGS="-target x86_64-apple-darwin"
$ cargo build
```

??????

so the target isn't propagating correctly?

```
--- a/build.rs
+++ b/build.rs
@@ -4,6 +4,7 @@
     // Use environment variable if set
     println!("cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH");
     if let Ok(path) = std::env::var("COREAUDIO_SDK_PATH") {
+        println!("cargo:warning=Using SDK path from env: {}", path);
         return Ok(path);
     }
 
@@ -29,6 +30,7 @@
         .output()?
         .stdout;
     let prefix_str = std::str::from_utf8(&output).expect("invalid output from `xcrun`");
+    println!("cargo:warning=Using SDK path: {}", prefix_str.trim_end());
     Ok(prefix_str.trim_end().to_string())
 }
 
@@ -114,11 +116,16 @@
     }
 
     println!("cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS");
+    println!(
+        "cargo:warning=bindgen extra clang args: '{}'",
+        env::var("BINDGEN_EXTRA_CLANG_ARGS").unwrap_or_else(|_| "none".to_string())
+    );
     // Get the cargo out directory.
     let out_dir = PathBuf::from(env::var("OUT_DIR").expect("env variable OUT_DIR not found"));
 
     // Begin building the bindgen params.
     let mut builder = bindgen::Builder::default();
+    println!("hello from build.rs, target: {}", target);
 
     // See https://github.com/rust-lang/rust-bindgen/issues/1211
     // Technically according to the llvm mailing list, the argument to clang here should be
@@ -133,8 +140,10 @@
     builder = builder.size_t_is_usize(true);
 
     builder = builder.clang_args(&[&format!("--target={}", target)]);
+    println!("cargo:warning=bindgen target: '{}'", target);
 
     if let Some(sdk_path) = sdk_path {
+        println!("cargo:warning=bindgen sing SDK path: {}", sdk_path);
         builder = builder.clang_args(&["-isysroot", sdk_path]);
     }
```

adding even more to `build.rs` to try to debug, and now I can't get it to fail.

So I'm going to close this. Maybe someone else will hit it and this could be a jump to start debugging again.

**Comment by simlay** [comment]
I'm glad you got it working! Though, in the future, there should be less friction as bevy/cpal/coreaudio-rs will use the objc2 bindings rather than bindgen. https://github.com/bevyengine/bevy/pull/19498.

Looking at some of the errors you saw, https://github.com/RustAudio/coreaudio-sys/issues/115 is similar. It was an issue with the `LIBCLANG_PATH` being set by the esp tooling.

**Comment by tschundler** [comment]
incidentally, I do also have Rust ESP32 setup. So maybe that was it. I searched issues before posting, but maybe I only searched open issues.

Maybe I should be friends with @Sycrosity - since we're apparently both fussing with bevy + embedded rust.
