### ISSUE TITLE
iOS Build fails with Xcode 16.1 / iOS 18.1

### ISSUE THREAD

**Issue by joe-wd** [RustAudio/coreaudio-sys#110]
Build fails with Xcode 16.1 / iOS 18.1, but works with older Xcode 15.1

Any advice here? I'm trying to go through the build.rs, but haven't figured out how to fix this.
Thanks for any help.

System:

- MacBook M1 Pro
- Sequoia 15.1.1
- Xcode 16.1 / iOS 18.1

Various failure messages:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1654:8: error: unknown type name 'ItemCount'

Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:43:11: fatal error: 'AudioToolbox/AudioFileComponent.h' file not found

Cargo.toml:
```
[package]
name = "test_coreaudio"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
coreaudio-sys = "0.2.16"
```

To reproduce:

```
% cargo --version
cargo 1.83.0 (5ffbef321 2024-10-29)

% rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.83.0 (90b35a623 2024-11-26)`

% rustup target list | grep ios                   
aarch64-apple-ios (installed)
aarch64-apple-ios-macabi
aarch64-apple-ios-sim (installed)
x86_64-apple-ios
x86_64-apple-ios-macabi

% cargo new test_coreaudio --lib
% cd test_coreaudio

% clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Applications/Xcode2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

% cargo build --target aarch64-apple-ios
   Compiling glob v0.3.1
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.14
   Compiling libc v0.2.167
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.4
   Compiling minimal-lexical v0.2.1
   Compiling regex-syntax v0.8.5
   Compiling libloading v0.8.6
   Compiling either v1.13.0
   Compiling bindgen v0.70.1
   Compiling shlex v1.3.0
   Compiling itertools v0.13.0
   Compiling nom v7.1.3
   Compiling bitflags v2.6.0
   Compiling clang-sys v1.8.1
   Compiling rustc-hash v1.1.0
   Compiling quote v1.0.37
   Compiling regex-automata v0.4.9
   Compiling syn v2.0.90
   Compiling cexpr v0.6.0
   Compiling regex v1.11.1
   Compiling coreaudio-sys v0.2.16
   Compiling test_coreaudio v0.1.0 (/Users/joe/dev/practice/bug/test_coreaudio)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 10.29s

% sudo xcode-select --switch /Applications/Xcode.app

% clang --version
Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

% cargo clean
Removed 650 files, 341.9MiB total

% cargo build --target aarch64-apple-ios
   Compiling proc-macro2 v1.0.92
   Compiling glob v0.3.1
   Compiling libc v0.2.167
   Compiling unicode-ident v1.0.14
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.4
   Compiling minimal-lexical v0.2.1
   Compiling regex-syntax v0.8.5
   Compiling libloading v0.8.6
   Compiling bindgen v0.70.1
   Compiling either v1.13.0
   Compiling shlex v1.3.0
   Compiling itertools v0.13.0
   Compiling bitflags v2.6.0
   Compiling nom v7.1.3
   Compiling clang-sys v1.8.1
   Compiling rustc-hash v1.1.0
   Compiling regex-automata v0.4.9
   Compiling quote v1.0.37
   Compiling syn v2.0.90
   Compiling cexpr v0.6.0
   Compiling regex v1.11.1
   Compiling coreaudio-sys v0.2.16
error: failed to run custom build command for `coreaudio-sys v0.2.16`

Caused by:
  process didn't exit successfully: `/Users/joe/dev/practice/bug/test_coreaudio/target/debug/build/coreaudio-sys-8d9360e859c6be68/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH
  cargo:rustc-link-lib=framework=AudioToolbox
  cargo:rustc-link-lib=framework=AudioToolbox
  cargo:rustc-link-lib=framework=CoreAudio
  cargo:rustc-link-lib=framework=OpenAL
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1654:8: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1685:16: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1698:8: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1716:7: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1732:8: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1750:7: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1763:8: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1781:8: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1808:8: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1823:16: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1834:8: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1849:21: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2093:8: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2110:24: error: unknown type name 'ItemCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2621:6: error: unknown type name 'ByteCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2624:6: error: unknown type name 'ByteCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2705:6: error: unknown type name 'ByteCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2708:6: error: unknown type name 'ByteCount'
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:43:11: fatal error: 'AudioToolbox/AudioFileComponent.h' file not found
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:43:11: note: did not find header 'AudioFileComponent.h' in framework 'AudioToolbox' (loaded from '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks')
  thread 'main' panicked at /Users/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/coreaudio-sys-0.2.16/build.rs:162:39:
  unable to generate bindings: ClangDiagnostic("/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1654:8: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1685:16: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1698:8: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1716:7: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1732:8: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1750:7: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1763:8: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1781:8: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1808:8: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1823:16: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1834:8: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1849:21: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2093:8: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2110:24: error: unknown type name 'ItemCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2621:6: error: unknown type name 'ByteCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2624:6: error: unknown type name 'ByteCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2705:6: error: unknown type name 'ByteCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:2708:6: error: unknown type name 'ByteCount'\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.1.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:43:11: fatal error: 'AudioToolbox/AudioFileComponent.h' file not found\n")
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
     1: core::panicking::panic_fmt
               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
     2: core::result::unwrap_failed
               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/result.rs:1700:5
     3: core::result::Result<T,E>::expect
               at /Users/joe/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1061:23
     4: build_script_build::build
               at ./build.rs:162:20
     5: build_script_build::main
               at ./build.rs:177:5
     6: core::ops::function::FnOnce::call_once
               at /Users/joe/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by simlay** [comment]
Hi! Thanks for the detailed report! I installed Xcode 16.1 the iOS 18.1 runtime to try and repro your issue but it builds as desired.

I know it's not all that helpful but perhaps you're iOS runtime SDK is somehow broken? Like, it's weird that `fatal error: 'AudioToolbox/AudioFileComponent.h' file not found` is in the error. It's pretty annoying but I'd try deleting the iOS Platform in the xcode settings Components panel and re-installing it (you can also do this with `xcrun simctl runtime`).

Alternatively, maybe your system is using a different version of clang/LLVM. To test this issue I had to unset `LIBCLANG_PATH` as I've been messing around with the [esp tooling](https://github.com/esp-rs/espup).

**Comment by joe-wd** [comment]
Thanks for the reply! I already tried reinstalling iOS 18.1 but to no avail. :(  I will try messing with my environment a bit, and try to get a coworker to reproduce as well.

I did find this in the 18.1 AudioToolbox.h header (line 41), suggesting that it shouldn't be looking for `AudioToolbox/AudioFileComponent.h` at all unless building for macOS. The same appears in 17.2, which works fine for me, so I guess it could be something wrong with my tooling env for 18.1.

```C
#if !TARGET_OS_IPHONE
	// macOS only
	#include <AudioToolbox/AudioFileComponent.h>
	#include <AudioToolbox/AUMIDIController.h>
	#include <AudioToolbox/CoreAudioClock.h>
#endif

#if TARGET_OS_OSX || TARGET_OS_IOS
	#include <AudioToolbox/AudioSession.h>
#endif
```

**Comment by joe-wd** [comment]
OK, this is resolved. Apparently something wrong with my Xcode or command line tools. In case anyone with a similar problem happens upon this, I resolved it as follows:

- I nuked all simulators
- I nuked /Applications/Xcode.app
- I nuked /Library/Developer
- Reinstalled XCode from the store
- Launched Xcode and let it download iOS 18.1

That seems to have solved the problem.

@simlay Thanks for your help. Closing this issue.
